/* Auto-generated by slice types generate. Do not edit manually. */

export interface ApexChartServicesProps {
  [key: string]: unknown;
}

export interface ApiServicesProps {
  [key: string]: unknown;
}

export interface ButtonProps {
  [key: string]: unknown;
  customColor?: Record<string, unknown>;
  icon?: Record<string, unknown>;
  onClickCallback?: (...args: unknown[]) => unknown;
  value?: string;
}

export interface CardProps {
  [key: string]: unknown;
  actions?: unknown[];
  badge?: string;
  customColor?: Record<string, unknown>;
  details?: string;
  disabled?: boolean;
  icon?: Record<string, unknown>;
  image?: string;
  interactive?: boolean;
  isOpen?: boolean;
  loading?: boolean;
  onClick?: (...args: unknown[]) => unknown;
  progress?: number;
  text?: string;
  title?: string;
  variant?: string;
}

export interface CheckboxProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: string;
  disabled?: boolean;
  label?: string;
  labelPlacement?: string;
}

export interface CodeVisualizerProps {
  [key: string]: unknown;
}

export interface DetailsProps {
  [key: string]: unknown;
  text?: string;
  title?: string;
}

export interface DropDownProps {
  [key: string]: unknown;
  label?: string;
  options?: unknown[];
}

export interface ElementCarrouselProps {
  [key: string]: unknown;
}

export interface FetchManagerProps {
  [key: string]: unknown;
}

export interface GoalsProps {
  [key: string]: unknown;
}

export interface GraphicsProps {
  [key: string]: unknown;
  accentColor?: string;
  categories?: unknown[];
  currentValue?: number;
  height?: number;
  series?: unknown[];
  title?: string;
  totalValue?: number;
  type?: string;
  width?: unknown;
}

export interface GridProps {
  [key: string]: unknown;
  columns?: string;
  columnTemplate?: string;
  gap?: string;
  items?: unknown[];
  rows?: number;
  rowTemplate?: string;
}

export interface HeaderProps {
  [key: string]: unknown;
  items?: unknown[];
  title?: string;
}

export interface HomePageProps {
  [key: string]: unknown;
}

export interface IconProps {
  [key: string]: unknown;
  color?: string;
  iconStyle?: string;
  name?: string;
  size?: string;
}

export interface IndexedDbManagerProps {
  [key: string]: unknown;
}

export interface InputProps {
  [key: string]: unknown;
  conditions?: Record<string, unknown>;
  disabled?: boolean;
  placeholder?: string;
  required?: boolean;
  secret?: boolean;
  type?: string;
  value?: string;
}

export interface LayoutProps {
  [key: string]: unknown;
  layout?: Record<string, unknown>;
  view?: Record<string, unknown>;
}

export interface LinkProps {
  [key: string]: unknown;
  classes?: string;
  path?: string;
  text?: string;
}

export interface LoadingProps {
  [key: string]: unknown;
  container?: Record<string, unknown>;
  isActive?: boolean;
}

export interface LocalStorageManagerProps {
  [key: string]: unknown;
}

export interface LoginProps {
  [key: string]: unknown;
}

export interface ModalProps {
  [key: string]: unknown;
}

export interface MultiRouteProps {
  [key: string]: unknown;
}

export interface NavbarProps {
  [key: string]: unknown;
  buttons?: unknown[];
  direction?: string;
  items?: unknown[];
  logo?: Record<string, unknown>;
  position?: string;
}

export interface NotFoundProps {
  [key: string]: unknown;
}

export interface PlaygroundProps {
  [key: string]: unknown;
}

export interface RegisterProps {
  [key: string]: unknown;
}

export interface RouteProps {
  [key: string]: unknown;
}

export interface SearchBarProps {
  [key: string]: unknown;
}

export interface SelectProps {
  [key: string]: unknown;
  disabled?: boolean;
  label?: string;
  multiple?: boolean;
  onOptionSelect?: (...args: unknown[]) => unknown;
  options?: unknown[];
  visibleProp?: string;
}

export interface SettingsProps {
  [key: string]: unknown;
}

export interface SidebarProps {
  [key: string]: unknown;
  buttons?: unknown[];
  direction?: string;
  items?: unknown[];
  position?: string;
  title?: string;
}

export interface StatisticsProps {
  [key: string]: unknown;
}

export interface SvgIconProps {
  [key: string]: unknown;
  color?: string;
  nombre?: string;
  size?: string;
}

export interface SwitchProps {
  [key: string]: unknown;
  checked?: boolean;
  customColor?: string;
  disabled?: boolean;
  label?: string;
  labelPlacement?: string;
  toggle?: (...args: unknown[]) => unknown;
}

export interface TableProps {
  [key: string]: unknown;
  headers?: unknown[];
  rows?: unknown[];
}

export interface TabsProps {
  [key: string]: unknown;
}

export interface TargetProps {
  [key: string]: unknown;
  context?: unknown[];
  variant?: string;
}

export interface TargetGoalsProps {
  id?: number;
  icon?: string;
  title?: string;
  titulo?: string;
  category?: string;
  current?: number;
  monto_actual?: string | number;
  total?: number;
  monto_objective?: string | number; // Fallback typo
  monto_objetivo?: string | number;
  targetDate?: string;
  fecha_limite?: string;
  completed?: boolean;
  onEdit?: (component: TargetGoals) => void;
  onDelete?: (component: TargetGoals) => void;
  onComplete?: (component: TargetGoals) => void;
}

export interface ThemeSelectorProps {
  [key: string]: unknown;
}

export interface ThemeSwitcherProps {
  [key: string]: unknown;
  label?: string;
  onChange?: (...args: unknown[]) => unknown;
  themes?: unknown[];
  variant?: "button" | "menu-item";
}

export interface TransactionProps {
  [key: string]: unknown;
}

export interface TreeItemProps {
  [key: string]: unknown;
  items?: unknown[];
  onClickCallback?: (...args: unknown[]) => unknown;
  path?: string;
  value?: string;
}

export interface TreeViewProps {
  [key: string]: unknown;
  items?: unknown[];
  onClickCallback?: (...args: unknown[]) => unknown;
}

export interface SliceComponentPropsMap {
  ApexChartServices: ApexChartServicesProps;
  ApiServices: ApiServicesProps;
  Button: ButtonProps;
  Card: CardProps;
  Checkbox: CheckboxProps;
  CodeVisualizer: CodeVisualizerProps;
  Details: DetailsProps;
  DropDown: DropDownProps;
  ElementCarrousel: ElementCarrouselProps;
  FetchManager: FetchManagerProps;
  Goals: GoalsProps;
  Graphics: GraphicsProps;
  Grid: GridProps;
  Header: HeaderProps;
  HomePage: HomePageProps;
  Icon: IconProps;
  IndexedDbManager: IndexedDbManagerProps;
  Input: InputProps;
  Layout: LayoutProps;
  Link: LinkProps;
  Loading: LoadingProps;
  LocalStorageManager: LocalStorageManagerProps;
  Login: LoginProps;
  Modal: ModalProps;
  MultiRoute: MultiRouteProps;
  Navbar: NavbarProps;
  NotFound: NotFoundProps;
  Playground: PlaygroundProps;
  Register: RegisterProps;
  Route: RouteProps;
  SearchBar: SearchBarProps;
  Select: SelectProps;
  Settings: SettingsProps;
  Sidebar: SidebarProps;
  Statistics: StatisticsProps;
  SvgIcon: SvgIconProps;
  Switch: SwitchProps;
  Table: TableProps;
  Tabs: TabsProps;
  Target: TargetProps;
  TargetGoals: TargetGoalsProps;
  ThemeSelector: ThemeSelectorProps;
  ThemeSwitcher: ThemeSwitcherProps;
  Transaction: TransactionProps;
  TreeItem: TreeItemProps;
  TreeView: TreeViewProps;
}

export type SliceComponentName = keyof SliceComponentPropsMap;
export type SliceDynamicElement = HTMLElement & Record<string, any>;

declare global {
  const slice: SliceBuildApi & Record<string, any>;

  interface Event {
    detail: any;
    key: any;
    request: any;
    waitUntil: any;
    respondWith: any;
    target: any;
    currentTarget: any;
  }

  interface Element {
    querySelectorAll<E extends Element = HTMLElement>(
      selectors: string,
    ): NodeListOf<E>;
  }
  interface HTMLElement {
    [key: string]: any;
  }
  interface EventTarget {
    [key: string]: any;
  }

  interface SliceBuildApi {
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K],
    ): Promise<SliceDynamicElement | null>;
  }
}

declare module "slicejs-web-framework" {
  interface SliceApi {
    build<K extends SliceComponentName>(
      name: K,
      props?: SliceComponentPropsMap[K],
    ): Promise<SliceDynamicElement | null>;
    getComponent<T extends SliceDynamicElement = SliceDynamicElement>(
      componentSliceId: string,
    ): T | undefined;
  }
}

export {};
